### ISSUE TITLE
Create Reusable Homebrew Auto-Update GitHub Action

### ISSUE THREAD

**Issue by cajias** [cajias/custom-github-actions#1]
# Homebrew Auto-Update GitHub Action

## Overview
This ticket outlines the requirements for a reusable GitHub Action to automatically update Homebrew formula when a project is released.

## Background
We've implemented a GitHub Actions workflow in the `cajias/zi` repository that automatically updates a Homebrew formula in the `cajias/homebrew-tools` repository whenever changes are pushed to the main branch. We want to extract this pattern into a reusable GitHub Action.

## Current Implementation
The current workflow (`.github/workflows/update-homebrew-tap.yml`) does the following:

1. Triggers on pushes to the main branch that modify specific files
2. Creates a versioned release tag based on date and commit hash
3. Creates a GitHub Release
4. Checks out the homebrew-tools repository
5. Updates the formula with the new version and SHA256
6. Commits and pushes the changes to the homebrew-tools repository

### Input Parameters
- `github_token`: GitHub token with appropriate permissions
- `tap_repo_token`: Token with write access to the Homebrew tap repository
- `github_user`: GitHub username of the repository owner
- `source_repo`: Repository containing the source code
- `tap_repo`: Repository containing the Homebrew tap
- `formula_name`: Name of the formula file to update
- `formula_path`: Path to the formula file within the tap repository
- `version_strategy`: How to generate the version (date-based, semver, etc.)
- `paths_to_watch`: Files that trigger the workflow when changed
- `custom_release_notes`: Optional custom release notes template

### Functionality
1. **Version Generation:**
   - Support different versioning strategies (date-based, semver from tags, etc.)
   - Allow for custom version formatting

2. **Release Creation:**
   - Create appropriate tags based on the versioning strategy
   - Generate GitHub releases with customizable notes

3. **Formula Update:**
   - Calculate SHA256 for the release tarball
   - Update version, URL, and SHA256 in the formula
   - Support custom formula templates

4. **Commit & Push:**
   - Commit changes to the tap repository with appropriate commit messages
   - Handle authentication securely

### Repository Structure
The action should be implemented in the `cajias/custom-github-actions` repository with:

- Main action implementation
- Documentation with examples
- Test workflows for validation
- Reusable templates

## Examples
Example workflow using the action:

```yaml
name: Update Homebrew Formula

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: cajias/custom-github-actions/update-homebrew@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tap_repo_token: ${{ secrets.TAP_REPO_TOKEN }}
          github_user: username
          source_repo: my-project
          tap_repo: homebrew-tools
          formula_name: my-formula
          formula_path: Formula/my-formula.rb
          version_strategy: date-commit
```

## Additional Considerations
- Security best practices for handling tokens
- Error handling and reporting
- Testing across different environments
- Documentation for setup and usage
